### ISSUE TITLE
terraform init

### ISSUE THREAD

**Issue by Amrosx** [SyntropyNet/syntropy-blockchain-integrations#9]
terraform --version
![image](https://user-images.githubusercontent.com/37171239/128677828-a14d876d-c98a-476b-b892-10b27c1ca5c9.png)

enviroment
![image](https://user-images.githubusercontent.com/37171239/128677415-1a7645f3-01dd-4e56-9705-e3ac3a748f6b.png)

![image](https://user-images.githubusercontent.com/37171239/128677205-5344db67-5d90-47fe-bfed-7a06055c689e.png)

when I run **terraform init**   I got this problem 

![image](https://user-images.githubusercontent.com/37171239/128677018-3a96e9f2-48e6-465a-8c27-d000a87ac643.png)

**Comment by Omranic** [comment]
Thank you @Amrosx for your question.

However to help you best I'd suggest you [open a ticket](https://syntropy.atlassian.net/servicedesk/customer/portals) and the team will take care of it, as this is not related to this development repo.

Once you create a ticket there, the team will followup with you on that ticket. Also, make sure you check our [Documentation platform](https://docs.syntropystack.com/docs). We are constantly updating and improving it, so you will find most of the answers to your questions there, as well.
